id: I30BF040B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T01:32:54+00:00'
last_modified: '2022-06-08T03:14:08.015315+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03811
  title: 'རྨ་ལྷོ་སོག་རིགས་རང་སྐྱོང་རྫོང་གི་དེབ་ཐེར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E4DA:
      image_group_id: I1PD90083
      title: ''
      total_pages: 646
      order: 1
      base_file: E4DA.txt
    DFDB:
      image_group_id: I1PD90084
      title: ''
      total_pages: 584
      order: 2
      base_file: DFDB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
