id: I30BF040B
legacy_id: P005459
ocr_import_info:
  bdrc_scan_id: W00KG03811
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T01:28:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:05:55.805273+00:00'
last_modified: 2022-08-30 22:08:07.723539
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG03811
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG03811
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: 河南蒙古族自治县志 / 河南蒙古族自治县方志编纂委员会编.
statistics:
  ocr_word_mean_confidence_index: 0.9196311800457322
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1PD90084:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD90084
      total_pages: 584
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD90084.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9174875494298393
    legacy_id: v002
  I1PD90083:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD90083
      total_pages: 646
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD90083.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9212275146861859
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
