id: P005459
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG03811
  title: 'རྨ་ལྷོ་སོག་རིགས་རང་སྐྱོང་རྫོང་གི་དེབ་ཐེར། '
  author: ''
  volumes:
    f1aa719880804c10937c217933b7fc0a:
      image_group_id: I1PD90083
      title: ''
      volume_number: 1
      total_pages: 646
    8528ccbb6f2b43038e9e50aa57e7d425:
      image_group_id: I1PD90084
      title: ''
      volume_number: 2
      total_pages: 584
